import turtle
Bob = turtle.Turtle()
screen = turtle.Screen()
smile = screen.register_shape('smile.gif')
Bob.shape('smile.gif')
Bob.penup()
# for i in range(50):
Bob.stamp()
Bob.forward(100)
Bob.stamp()
Bob.forward(100)
Bob.stamp()
Bob.forward(10)
Bob.stamp()
Bob.forward(10)
Bob.stamp()
Bob.forward(10)
Bob.stamp()
Bob.forward(10)
# Bob.forward(200)
# Bob.right(144)